<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_9788550801483</name>
   <tag></tag>
   <elementGuidId>9ad1dffd-f640-4d38-bc9f-4b81b7676668</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='info-section']/div[2]/section/div/div/div[3]/table/tbody/tr[5]/td[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextUI-sc-1hrwx40-0 btzHBm</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>9788550801483</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;info-section&quot;)/div[@class=&quot;ColUI-sc-1ey7nd2-0 cVzwsq ViewUI-oocyw8-6 kvewNe&quot;]/section[@class=&quot;CardUI-sc-1sw801q-0 eRybUp&quot;]/div[@class=&quot;ColUI-sc-1ey7nd2-0 bnEfmp ViewUI-oocyw8-6 kvewNe&quot;]/div[@class=&quot;GridUI-sc-1f6kp3y-0 fZYRLL ViewUI-oocyw8-6 kvewNe&quot;]/div[@class=&quot;ColUI-sc-1ey7nd2-0 duTvSh ViewUI-oocyw8-6 kvewNe&quot;]/table[@class=&quot;TableUI-o6rohr-0 kJZaBa&quot;]/tbody[@class=&quot;TBody-sc-6kkk7q-2 dhnoaX&quot;]/tr[@class=&quot;Tr-sc-6kkk7q-3 bwaahg&quot;]/td[@class=&quot;Td-sc-6kkk7q-5 fMvJBL&quot;]/span[@class=&quot;TextUI-sc-1hrwx40-0 btzHBm&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='info-section']/div[2]/section/div/div/div[3]/table/tbody/tr[5]/td[2]/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ISBN'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Starlin'])[1]/following::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coleção'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAI RICO PAI POBRE'])[1]/preceding::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//tr[5]/td[2]/span</value>
   </webElementXpaths>
</WebElementEntity>
